package com.example.shopper;

import android.content.Intent;
import android.os.Bundle;

import com.google.android.material.floatingactionbutton.FloatingActionButton;
import com.google.android.material.snackbar.Snackbar;

import androidx.appcompat.app.AppCompatActivity;
import androidx.appcompat.widget.Toolbar;

import android.view.View;
import android.view.Menu;
import android.view.MenuItem;
import android.widget.AdapterView;
import android.widget.ListView;

public class MainActivity extends AppCompatActivity {

    //declare an intent
    Intent intent;

    // declare a database Handler
    DBHandler dbHandler;

    // Declare a shoppinglist cursor adapter
    ShoppingLists shoppingListsAdapter;

    // declare a list view
    ListView shopperListView;

    /**
     *This method initializes the Action Bar and the view
     * of the Main Activity
     * @param savedInstanceState
     */
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        // This code generated by Android Studio initializes
        // the view and the Action Bar of the Main Activity
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        Toolbar toolbar = findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);

        // initialize the database handler
        dbHandler = new DBHandler(this, null);

        // initialize the list view
        shopperListView = (ListView) findViewById(R.id.shopperListView);

        // initialize the Shopping Lists Cursor Adapter
        shoppingListsAdapter = new ShoppingLists(this, dbHandler.getShoppingLists(), 0);

        // set the Shopping Lists Cursor Adapter on ListView
        shopperListView.setAdapter(shoppingListsAdapter);

        // set OnItemClickListener to shopper ListView
        shopperListView.setOnItemClickListener(new AdapterView.OnItemClickListener() {
            @Override
            public void onItemClick(AdapterView<?> adapterView, View view, int position, long id) {
                // launch the view list activity and sending it the id of
                // the shopping list
                intent = new Intent(MainActivity.this, ViewList.class);
                intent.putExtra("_id", id);
                startActivity(intent);
            }
        });
    }

    /**
     * This method further initializes the action bar of the main activity
     * It gets the code we wrote in the menu main and incorporates it into the
     * action bar.
     * @param menu
     * @return
     */
    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        // Inflate the menu; this adds items to the action bar if it is present.
        getMenuInflater().inflate(R.menu.menu_main, menu);
        return true;
    }

    /**
     * This method gets called when an item in the overflow menu is selected and it
     * controls what happens when the item is selected
     * @param item item is selected in the overflow menu
     * @return true if an item was selected; else return false
     */
    @Override
    public boolean onOptionsItemSelected(MenuItem item) {

        // get the id of the item that was selected
        switch(item.getItemId()){
            case R.id.action_home :
                // initializing an intent for the Create List activity, starting it
                // and returning home
                intent = new Intent(this, MainActivity.class);
                startActivity(intent);
                return true;
            case R.id.action_create_list:
                // initializing an intent for the Main activity, starting it
                // and returning home
                intent = new Intent(this, CreateList.class);
                startActivity(intent);
                return true;
                default:
                    return super.onOptionsItemSelected(item);
        }

    }

    /**
     * When you click the floating action button it starts the
     * Create List Activity
     * @param view
     */
    public void openCreateList(View view) {
        // initializing an intent for the Main activity, and starting it
        intent = new Intent(this, CreateList.class);
        startActivity(intent);
    }
}
